// // src/app/layout.tsx
// import './globals.css';
// import type { Metadata } from 'next';
// import FooterComponent from './Components/FooterComponent/FooterComponent';
// import ServicesComponent from './Components/ServicesComponent/ServicesComponent';
// import AboutComponent from './Components/AboutComponent/AboutComponent';
// import TestimonialsComponent from './Components/TestimonialsComponent/TestimonialsComponent';

// export const metadata: Metadata = {
//   title: 'AlphaDevs',
//   description: 'Generated by create next app',
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body>
//         {children} 
//         <ServicesComponent />     
//         <AboutComponent />        
//         <TestimonialsComponent /> 
//         <FooterComponent />
//       </body>
//     </html>
//   );
// }

import ClientLayout from './Components/ClientLayout';
import './globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'AlphaDevs',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
